{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d47f2256_d685a47a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1001264
      },
      "writtenOn": "2024-09-19T00:46:19Z",
      "side": 1,
      "message": "Hi reviewers,\nI just rebase and update the legacy.json to fix the error from validate_configs.py.\nPlease kindly help review the changes, thank you.",
      "revId": "3bd86e2fdb3a9cd42de42b0af8ed98af38b44a3e",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ],
  "submitRequirementResults": []
}