{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f38e95bd_dbfe0619",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 13
      },
      "lineNbr": 0,
      "author": {
        "id": 1000546
      },
      "writtenOn": "2022-03-14T06:27:23Z",
      "side": 1,
      "message": "Looks like master branch itself has this CI issue. \nTested with master branch with my local CI setup.\n\n\" \nusr/local/include/sdbusplus/asio/object_server.hpp:120:16:   required from ‘int sdbusplus::asio::callback_method_instance\u003cCallbackType\u003e::call(sdbusplus::message_t\u0026) [with CallbackType \u003d main()::\u003clambda(uint8_t, uint8_t, const std::vector\u003cunsigned char\u003e\u0026)\u003e; sdbusplus::message_t \u003d sdbusplus::message::message]’\n/usr/local/include/sdbusplus/asio/object_server.hpp:118:9:   required from here\n/usr/local/include/sdbusplus/asio/object_server.hpp:131:14: error: ‘void r’ has incomplete type\n  131 |         auto r \u003d std::apply(func_, inputArgs);\n      \n\"          ^",
      "revId": "7eaeb7ccd92e59669b070a960e0efdd6a874665f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}